
- name: put nginx config
  become: true
  become_user: root
  template:
    src=config
    dest=/etc/nginx/sites-available/{{ app_name }}.conf
    backup=yes

- name: link to enabled
  become: true
  become_user: root
  file:
    src=/etc/nginx/sites-available/{{ app_name }}.conf
    dest=/etc/nginx/sites-enabled/default
    owner=root
    group=root
    state=link

- name: reload nginx
  become: true
  become_user: root
  service: name=nginx state=reloaded
